apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2023-01-17T14:04:23Z"
  generation: 2
  labels:
    app: hog
  name: hog
  namespace: default
  resourceVersion: "15975"
  uid: 3988ef41-fcd4-4795-87b8-7506bb026ee3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hog
    spec:
      containers:
        - args:
            - -cpus
            - "2"
            - -mem-total
            - 1500Mi
            - -mem-alloc-size
            - 300Mi
            - -mem-alloc-sleep
            - 6s
          image: vish/stress
          imagePullPolicy: Always
          name: stress
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
    - lastTransitionTime: "2023-01-17T14:04:23Z"
      lastUpdateTime: "2023-01-17T14:09:41Z"
      message: ReplicaSet "hog-79ffc6ff65" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2023-01-17T14:14:39Z"
      lastUpdateTime: "2023-01-17T14:14:39Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
